[package]
name = "bevy_mod_adwaita"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "e7b83acadcdca3f5d4864944f43f21d4784f35fe", default-features = false, features = [
  "bevy_asset",
  "bevy_render",
  "bevy_winit",
  "wayland",
] }

tracing = "0.1.40"
oneshot = "0.1.8"
flume = "0.11.0"

[dependencies.adw]
package = "libadwaita"
version = "0.7.0"

[dependencies.gtk]
package = "gtk4"
version = "0.9.2"
features = ["v4_16"]

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "e7b83acadcdca3f5d4864944f43f21d4784f35fe" }
